/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Counter } from './Counter.js';
export type { VerixaRegistry } from './VerixaRegistry.js';
export * as factories from './factories/index.js';
export { Counter__factory } from './factories/Counter__factory.js';
export { VerixaRegistry__factory } from './factories/VerixaRegistry__factory.js';