/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface VerixaRegistryInterface extends Interface {
    getFunction(nameOrSignature: "records" | "register" | "verify"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "Registered"): EventFragment;

    encodeFunctionData(functionFragment: 'records', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'register', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'verify', values: [BytesLike]): string;

    decodeFunctionResult(functionFragment: 'records', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'register', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'verify', data: BytesLike): Result;
  }

  
    export namespace RegisteredEvent {
      export type InputTuple = [hash: BytesLike, owner: AddressLike, timestamp: BigNumberish];
      export type OutputTuple = [hash: string, owner: string, timestamp: bigint];
      export interface OutputObject {hash: string, owner: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface VerixaRegistry extends BaseContract {
    
    connect(runner?: ContractRunner | null): VerixaRegistry;
    waitForDeployment(): Promise<this>;

    interface: VerixaRegistryInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    records: TypedContractMethod<
      [arg0: BytesLike, ],
      [[string, bigint] & {owner: string, timestamp: bigint }],
      'view'
    >
    

    
    register: TypedContractMethod<
      [hash: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    verify: TypedContractMethod<
      [hash: BytesLike, ],
      [[boolean, string, bigint] & {exists: boolean, owner: string, timestamp: bigint }],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'records'): TypedContractMethod<
      [arg0: BytesLike, ],
      [[string, bigint] & {owner: string, timestamp: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'register'): TypedContractMethod<
      [hash: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'verify'): TypedContractMethod<
      [hash: BytesLike, ],
      [[boolean, string, bigint] & {exists: boolean, owner: string, timestamp: bigint }],
      'view'
    >;

    getEvent(key: 'Registered'): TypedContractEvent<RegisteredEvent.InputTuple, RegisteredEvent.OutputTuple, RegisteredEvent.OutputObject>;

    filters: {
      
      'Registered(bytes32,address,uint256)': TypedContractEvent<RegisteredEvent.InputTuple, RegisteredEvent.OutputTuple, RegisteredEvent.OutputObject>;
      Registered: TypedContractEvent<RegisteredEvent.InputTuple, RegisteredEvent.OutputTuple, RegisteredEvent.OutputObject>;
    
    };
  }